<a href="https://colab.research.google.com/github/Thing-ji/examples/blob/main/%EC%95%84%EC%9D%B4%EB%A6%AC%EC%8A%A4_%EB%B6%84%EB%A5%98(%EC%8B%A0%EA%B2%BD%EB%A7%9D_%EC%82%AC%EC%9A%A9).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import pandas as pd

In [ ]:
file = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
iris = pd.read_csv(file)

In [ ]:
iris.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [ ]:
iris = pd.get_dummies(iris)

In [ ]:
독립 = iris[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = iris[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [ ]:
# 모델 구조만들기
# 분류 문제에서는 activation: 활성화 함수를 사용해주어야 함.
# 회귀에선 mse, 분류에선 crossentropy

x = tf.keras.layers.Input(shape = [4])
y = tf.keras.layers.Dense(3, activation = 'softmax')(x)
model = tf.keras.models.Model(x, y)
model.compile(loss = 'categorical_crossentropy', metrics = 'accuracy')

In [ ]:
# 모델에 fit하기

model.fit(독립, 종속, epochs = 1000, verbose = 0)
model.fit(독립, 종속, epochs = 10)

Epoch 1/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1480 - accuracy: 0.9733
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1481 - accuracy: 0.9800
Epoch 3/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1480 - accuracy: 0.9800
Epoch 4/10
5/5 [==============================] - 0s 1ms/step - loss: 0.1477 - accuracy: 0.9733
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1476 - accuracy: 0.9800
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1471 - accuracy: 0.9800
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1476 - accuracy: 0.9800
Epoch 8/10
5/5 [==============================] - 0s 1ms/step - loss: 0.1471 - accuracy: 0.9800
Epoch 9/10
5/5 [==============================] - 0s 3ms/step - loss: 0.1470 - accuracy: 0.9733
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1468 - accuracy: 0.9800


In [ ]:
# 모델 이용하기

print(model.predict(독립[:5]))
print(종속[:5])

[[9.9925834e-01 7.4162142e-04 2.6061352e-08]
 [9.9662626e-01 3.3734727e-03 2.8326070e-07]
 [9.9855691e-01 1.4430204e-03 9.8860795e-08]
 [9.9611950e-01 3.8800326e-03 4.8233125e-07]
 [9.9942720e-01 5.7284522e-04 1.9859645e-08]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


In [ ]:
# 맨 마지막 데이터 5개

print(model.predict(독립[-5:]))
print(종속[-5:])

[[6.0265018e-07 1.2858124e-01 8.7141818e-01]
 [1.1369851e-06 1.9902590e-01 8.0097294e-01]
 [2.3562354e-06 2.3302016e-01 7.6697755e-01]
 [5.8121623e-07 8.8918500e-02 9.1108090e-01]
 [5.1866837e-06 2.5558299e-01 7.4441183e-01]]
     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1


In [ ]:
# 가중치 및 편향 출력하기
print(model.get_weights())

[array([[ 1.0193175 ,  0.6971136 , -0.45054042],
       [ 2.7208493 , -0.18526421, -1.468313  ],
       [-3.619884  , -0.27629942,  1.4874135 ],
       [-3.3850398 , -0.6071763 ,  2.5653548 ]], dtype=float32), array([ 1.9588532,  1.3309692, -1.6851704], dtype=float32)]


setosa = 1.0193175*w + 2.7208493*w2 ..